.data
 TN     DWORD 4     ;;; # of tests
 CASE   DWORD 5              ;;; list size (CASE: start of input)
 HEIGHT DWORD 1, 2, 1, 4, 6  ;;; heights measured(1st test)
        DWORD 10                                  ;;; list size(2nd test)
        DWORD 12, 18, 20, 20, 25, 3, 4, 4, 11, 1  ;;; height measured(2nd test)
        DWORD 11
        DWORD 8, 9, 9, 33, 43, 14, 19, 23, 23, 24, 50
		DWORD 3
		DWORD 1, 1, 1
